### ISSUE TITLE
有具体一点的文档吗

### ISSUE THREAD

**Issue by r1172464137** [KEEER/cloud-print-remote#1]
RT

**Comment by Alan-Liang** [comment]
感谢关注！

很抱歉，我们暂时还没有（除了 `DESIGN.md` 里的内容）。您是需要什么方面的帮助？现在您能跑起来吗？

这个服务需要 PostgreSQL 以及 KEEER 内部的帐号系统（<https://account.keeer.net/>，内部称为 `kas`，这几天在做安全检查，代码过几天发出来），以及配合 Endpoint 端使用。数据库的 table schema 在 `SQL_init.sql`。两个配置文件在 `server.config` 和 `endpoint.config`，可以参考相应的示例填写；此外，还需要一个 Remote 端的私钥和 Endpoint 端的公钥，分别放在 `remote_key.pem`（私钥）和 `endpoint_key.pem`（公钥）。配置完成之后运行 `python3 server.py` 即可。

有什么问题您也可以微信交流：`aHR0cHM6Ly9pLmxvbGkubmV0LzIwMjAvMDgvMTYvaXluSWo5YVd3Y0szcWZKLmpwZwo=`（微信二维码地址的 base64）
